### ISSUE TITLE
no train examples

### ISSUE THREAD

**Issue by longpeng2008** [dikatok/fast-deep-matting#1]
can you provide some train examples?

**Comment by dikatok** [comment]
Hi, you can download the data [here](https://drive.google.com/open?id=1O22ruj2bMhxqKbJPlADI4TBHqHTCDl6p) and create the tfrecords using create_tfrecords.py

Please do report if you are able to reproduce the result from [the paper](https://arxiv.org/abs/1707.08289) since I am still playing around with the feathering block and haven't been able to produce decent result

Thanks

**Comment by longpeng2008** [comment]
ok, thanks very much!

2018-02-05 9:55 GMT+08:00 Andika Tanuwijaya <notifications@github.com>:
